### ISSUE TITLE
Can't send value of zero from companion

### ISSUE THREAD

**Issue by mko1989** [josephdadams/midi-relay#9]
Hi,
I'm trying to control a Roland switcher using companion and your's software to change inputs in roland.
For this I need to send CC message with channel 1 to controller 12 and for input#1 value 0.
The problem is Midi Relay is interpreting companion's 0 as 1 and also companion's 1 as 1. Which makes choosing input 1 impossible. 
Don't know on which software is at fault here, but as I understand you are The Man behind both midi relay and it's module.
That's why I ask you to look into it.

Thanks

**Comment by josephdadams** [comment]
Hello, I believe this has been fixed in a recent update, however I have not created new binaries for midi-relay. You can run the source code directly if you like until I create new binaries. I will check to see if the Companion module has been updated to support zero values. I know the fix has been put in, but not sure if the update has been pushed to the core.

**Comment by josephdadams** [comment]
@mko1989 I have created new binaries with the 2.0.1 release. This fixes the '0' issues. The module in Companion will be patched this week before the upcoming release.
